server:
  port: 9296
  
spring:
  application:
    name: CLOUD-CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ty-hemadri/cloud-config
          clone-on-start: true
  